-- multi-users-ref.py 전용: Supabase 초기 스키마 + RLS + 벡터 검색 함수
-- 실행 위치: Supabase Dashboard -> SQL Editor
-- 이 스크립트는 idempotent(여러 번 실행 가능)하게 작성되었습니다.

-- 0) 확장
create extension if not exists vector;
create extension if not exists pgcrypto;

-- 1) 세션 테이블
create table if not exists public.sessions (
    id uuid primary key default gen_random_uuid(),
    session_id uuid unique,
    user_id uuid not null references auth.users (id) on delete cascade,
    title text not null default 'New Chat',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

alter table public.sessions
    add column if not exists session_id uuid,
    add column if not exists user_id uuid references auth.users (id) on delete cascade,
    add column if not exists title text not null default 'New Chat',
    add column if not exists created_at timestamptz not null default now(),
    add column if not exists updated_at timestamptz not null default now();

create index if not exists idx_sessions_user_id on public.sessions (user_id);
create index if not exists idx_sessions_updated_at_desc on public.sessions (updated_at desc);

-- 2) 메시지 테이블
create table if not exists public.messages (
    id bigint generated by default as identity primary key,
    session_id uuid not null references public.sessions (id) on delete cascade,
    role text not null check (role in ('user', 'ai')),
    content text not null,
    created_at timestamptz not null default now()
);

alter table public.messages
    add column if not exists session_id uuid references public.sessions (id) on delete cascade,
    add column if not exists role text,
    add column if not exists content text,
    add column if not exists created_at timestamptz not null default now();

create index if not exists idx_messages_session_id on public.messages (session_id);
create index if not exists idx_messages_created_at on public.messages (created_at);

-- 3) 문서/임베딩 테이블
create table if not exists public.documents (
    id bigint generated by default as identity primary key,
    content text not null,
    metadata jsonb not null default '{}'::jsonb,
    embedding vector,
    user_id text not null,
    created_at timestamptz not null default now()
);

alter table public.documents
    add column if not exists content text,
    add column if not exists metadata jsonb not null default '{}'::jsonb,
    add column if not exists embedding vector,
    add column if not exists user_id text,
    add column if not exists created_at timestamptz not null default now();

create index if not exists idx_documents_user_id on public.documents (user_id);
create index if not exists idx_documents_metadata_gin on public.documents using gin (metadata);
create index if not exists idx_documents_session_id_expr on public.documents ((metadata->>'session_id'));
-- ivfflat 인덱스는 데이터 적재 후 성능에 맞춰 lists 값을 조정하세요.
create index if not exists idx_documents_embedding_ivfflat
    on public.documents using ivfflat (embedding vector_cosine_ops);

-- 4) updated_at 자동 갱신
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists trg_sessions_updated_at on public.sessions;
create trigger trg_sessions_updated_at
before update on public.sessions
for each row
execute function public.set_updated_at();

-- 5) 벡터 검색 함수 (multi-users-ref.py 에서 rpc("match_documents", ...) 호출)
create or replace function public.match_documents(
    query_embedding vector,
    match_threshold double precision default 0.28,
    match_count integer default 40,
    filter_user_id text default null
)
returns table (
    id bigint,
    content text,
    metadata jsonb,
    similarity double precision
)
language sql
stable
set search_path = public
as $$
    select
        d.id,
        d.content,
        d.metadata,
        1 - (d.embedding <=> query_embedding) as similarity
    from public.documents d
    where
        d.embedding is not null
        and (filter_user_id is null or d.user_id = filter_user_id)
        and (1 - (d.embedding <=> query_embedding)) >= match_threshold
    order by d.embedding <=> query_embedding
    limit match_count;
$$;

grant usage on schema public to authenticated;
grant execute on function public.match_documents(vector, double precision, integer, text) to authenticated;

-- 6) RLS
alter table public.sessions enable row level security;
alter table public.messages enable row level security;
alter table public.documents enable row level security;

-- 기존 정책 정리
drop policy if exists "sessions_select_own" on public.sessions;
drop policy if exists "sessions_insert_own" on public.sessions;
drop policy if exists "sessions_update_own" on public.sessions;
drop policy if exists "sessions_delete_own" on public.sessions;

drop policy if exists "messages_select_own" on public.messages;
drop policy if exists "messages_insert_own" on public.messages;
drop policy if exists "messages_update_own" on public.messages;
drop policy if exists "messages_delete_own" on public.messages;

drop policy if exists "documents_select_own" on public.documents;
drop policy if exists "documents_insert_own" on public.documents;
drop policy if exists "documents_update_own" on public.documents;
drop policy if exists "documents_delete_own" on public.documents;

-- sessions: 본인 데이터만
create policy "sessions_select_own"
on public.sessions
for select
to authenticated
using (auth.uid() = user_id);

create policy "sessions_insert_own"
on public.sessions
for insert
to authenticated
with check (auth.uid() = user_id);

create policy "sessions_update_own"
on public.sessions
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "sessions_delete_own"
on public.sessions
for delete
to authenticated
using (auth.uid() = user_id);

-- messages: 소유한 세션에 속한 메시지만 허용
create policy "messages_select_own"
on public.messages
for select
to authenticated
using (
    exists (
        select 1
        from public.sessions s
        where s.id = messages.session_id
          and s.user_id = auth.uid()
    )
);

create policy "messages_insert_own"
on public.messages
for insert
to authenticated
with check (
    exists (
        select 1
        from public.sessions s
        where s.id = messages.session_id
          and s.user_id = auth.uid()
    )
);

create policy "messages_update_own"
on public.messages
for update
to authenticated
using (
    exists (
        select 1
        from public.sessions s
        where s.id = messages.session_id
          and s.user_id = auth.uid()
    )
)
with check (
    exists (
        select 1
        from public.sessions s
        where s.id = messages.session_id
          and s.user_id = auth.uid()
    )
);

create policy "messages_delete_own"
on public.messages
for delete
to authenticated
using (
    exists (
        select 1
        from public.sessions s
        where s.id = messages.session_id
          and s.user_id = auth.uid()
    )
);

-- documents: user_id(text) = auth.uid()::text
create policy "documents_select_own"
on public.documents
for select
to authenticated
using (user_id = auth.uid()::text);

create policy "documents_insert_own"
on public.documents
for insert
to authenticated
with check (user_id = auth.uid()::text);

create policy "documents_update_own"
on public.documents
for update
to authenticated
using (user_id = auth.uid()::text)
with check (user_id = auth.uid()::text);

create policy "documents_delete_own"
on public.documents
for delete
to authenticated
using (user_id = auth.uid()::text);
